### PR TITLE
Port to 1.20.4

### LINKED ISSUE #14: [Crash] Mixin error crash 1.20.4 v1.0.2
Game crashed when opening server list.
[crash-2024-01-11_11.47.57-client.txt](https://github.com/mrmelon54/draggable_lists/files/13897639/crash-2024-01-11_11.47.57-client.txt)
```
Description: mouseClicked event handler

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4267 failed
	at net.minecraft.class_500.<init>(class_500.java:54)
	at net.minecraft.class_442.method_19860(class_442.java:165)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:307)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4267 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 23 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 27 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-draggable_lists-common.mixins.json:server.MixinServerSelectionList from mod draggable_lists] from phase [DEFAULT] in config [fabric-draggable_lists-common.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 30 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: method_25394(Lnet/minecraft/class_332;IIF)V in fabric-draggable_lists-common.mixins.json:server.MixinServerSelectionList from mod draggable_lists overrides a final method from net.minecraft.class_339 [MAIN Applicator Phase -> fabric-draggable_lists-common.mixins.json:server.MixinServerSelectionList from mod draggable_lists -> Apply Methods -> (Lnet/minecraft/class_332;IIF)V:method_25394 ->  -> Validate]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.validateMethod(MixinTargetContext.java:540)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:465)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:535)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:521)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 30 more
```

### PR DESCRIPTION
**Pull request by dima-dencep**
Forge is now NeoForge, I also did some refactoring and removed the quilt since it didn't update to 1.20.4
And now this mod is independent of architectury.

Fixes #14 #13 #11

### CODE REVIEW

**Comment by mrmelon54** [comment]
Why did you remove forgix and getVersionMetadata?

**Comment by dima-dencep** [comment]
forgix is shit, and getVersionMetadata is what was used only there

**Comment by mrmelon54** [comment]
but why?

**Comment by dima-dencep** [comment]
Think, one jar file contains files designed for two completely different platforms

**Comment by mrmelon54** [comment]
I've had many users downloading the wrong platform jar, so if there is only one jar that works everywhere then boom no more issues

**Comment by dima-dencep** [comment]
Just teach them how to use modrinth site

**Comment by dima-dencep** [comment]
fabric will not load forge-mod, and forge will give a warning that a particular mod is for fabric

**Comment by mrmelon54** [comment]
Yea but I have more downloads on curseforge and not even I understand how to use that, especially the new UI

**Comment by dima-dencep** [comment]
How did you have the brains to write a mod if you couldn't handle such a simple site.

**Comment by mrmelon54** [comment]
also what happened with quilt?

**Comment by dima-dencep** [comment]
> removed the quilt since it didn't update to 1.20.4

**Comment by dima-dencep** [comment]
Anyway, the fabric version will work fine on it.

**Comment by mrmelon54** [comment]
> How did you have the brains to write a mod if you couldn't handle such a simple site.

The problem is that the UI is awful and I don't want to try and explain how to use websites to everyone who downloads my mods, because that is a waste of my time.

**Comment by Kikithecat12345** [comment]
> How did you have the brains to write a mod if you couldn't handle such a simple site.

It's almost like Curseforge's API and automations are proactively against developers who make the very content on their site. The new UI is much worse than the old one, because half of it does not function at all. 

> forgix is shit, and getVersionMetadata is what was used only there

How so? It works, and it lets @mrmelon54 compile the mod. What about it sucks? 

> And now this mod is independent of architectury.

The whole point of architectury is to have a single JAR. Why would you get rid of it?

> How did you have the brains to write a mod if you couldn't handle such a simple site.

I find this funny, because your PR barely works, and for it to be merged requires re-adding some of the things you removed. If anything, it's probably better to close this PR and rewrite it from scratch. 

@dima-dencep

**Comment by mrmelon54** [comment]
point noted

**Comment by Dreuzz** [comment]
LMAO

**Comment by GLDYM** [comment]
lmao

**Pull request closed without merging**
